server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;

        # Allow POST for SAML
        error_page 405 =200 /index.html;
    }
}